### ISSUE TITLE
emerge sys-auth/fprintd-1.90.1-r1 fails if systemd is not present, even if -systemd flag is set.

### ISSUE THREAD

**Issue by cloc3** [ulda/gentoo-ulda#1]
emerge sys-auth/fprintd-1.90.1-r1 fails if systemd is not present, even if -systemd flag is set.

[build.log](https://github.com/ulda/gentoo-ulda/files/4636627/build.log)
[emergeFprintd.info.log](https://github.com/ulda/gentoo-ulda/files/4636611/emergeFprintd.info.log)

**Comment by ulda** [comment]
I checked the sources:
It seems that the pam module  hard depends on systemd, no way to disable that.
So I have to remove the systemd use flag and hard code the systemd dependency or have some  (pam and systemd).

**Comment by ulda** [comment]
try 1.90.5 and look if elogind support works.
